# Generated by Django 3.1.5 on 2022-10-17 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('werken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='werken',
            name='opmerking',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='werken',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
