# Generated by Django 3.1.5 on 2022-10-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werken', '0002_auto_20221017_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='werken',
            name='opmerking2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
