# Generated by Django 4.1.2 on 2022-10-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werken', '0003_werken_opmerking2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
