# Generated by Django 4.1.2 on 2022-10-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('genre', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/images/')),
            ],
        ),
    ]
